crawler/urls.py
from crawler import views
from django.urls import path


app_name = 'crawler'
urlpatterns = [
    path('', views.crawler_index, name="index"),
    path('logs/', views.log_index, name="log-index"),
    path('logs/errors', views.log_errors, name="log-errors"),
    path('logs/<int:logstart_id>', views.log_one, name="log-one"),
    path('logs/<int:logstart_id>/errors', views.log_one_error, name="log-one-errors"),
    path('runs/', views.run_index, name="run-index"),
    path('runs/<int:run_id>/', views.run_detail, name="run-detail"),
    path('runs/<int:run_id>/cancel', views.run_cancel_hx, name="run-cancel"),
    path('runs/<int:run_id>/clear', views.run_remove_error_hx, name="run-remove-error"),
    path('runs/<int:run_id>/infinite', views.run_remove_limit_hx, name="run-remove-limit"),
    path('stats/', views.update_stats, name="update-stats"),
]

crawler/models.py
from django.db import models
from decklist.models import Deck, DataSource


class CrawlRun(models.Model):
    class State(models.IntegerChoices):
        NOT_STARTED = 0
        FETCHING_DECKS = 1
        COMPLETE = 5
        
        CANCELLED = 98
        ERROR = 99

    crawl_start_time = models.DateTimeField()
    # at the beginning of the run, we'll look for the newest deck
    # update we have from the source. if we see a timestamp older
    # than that, since we search from newest to oldest, we know
    # it's time to stop.
    search_back_to = models.DateTimeField(null=True, blank=True)
    target = models.IntegerField(choices=DataSource.choices)
    state = models.IntegerField(choices=State.choices)
    note = models.TextField(blank=True)
    next_fetch = models.URLField(blank=True)

    def __str__(self):
        return f"Run {self.id} [{self.get_target_display()}] ({self.crawl_start_time})"


class DeckCrawlResult(models.Model):
    url = models.URLField()
    deck = models.ForeignKey(
        Deck,
        on_delete=models.CASCADE,
    )
    # Last update time according to data source
    updated_time = models.DateTimeField()
    fetchable = models.BooleanField(default=True)
    got_cards = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.url}"


class LogStart(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    text = models.TextField(blank=True)

    def __str__(self):
        return self.text

    class Meta:
        ordering = ('-created',)


class LogEntry(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    text = models.TextField()
    parent = models.ForeignKey(
        LogStart,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
    )
    is_stderr = models.BooleanField(default=False)

    class Meta:
        ordering = ('-created',)
        verbose_name_plural = 'log entries'

    def __str__(self):
        return self.text

    def next(self):
        return self.logentry_set.first()

crawler/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator
from django.views.decorators.http import require_POST
from django_htmx.http import HttpResponseClientRefresh
from crawler.models import CrawlRun, LogEntry, LogStart
from decklist.models import Deck, SiteStat


def crawler_index(request):
    try:
        stats = SiteStat.objects.latest()
    except SiteStat.DoesNotExist:
        stats = None

    return render(
        request,
        'crawler/index.html',
        {
            'stats': stats,
            'user_logged_in': request.user.is_authenticated,
        },
    )


def run_index(request):
    runs = CrawlRun.objects.order_by('-crawl_start_time')
    paginator = Paginator(runs, 8, orphans=3)
    page_number = request.GET.get('page')
    runs_page = paginator.get_page(page_number)

    return render(
        request,
        'crawler/run_index.html',
        {
            'runs': runs_page,
        },
    )


def run_detail(request, run_id):
    run = get_object_or_404(CrawlRun, pk=run_id)

    return render(
        request,
        'crawler/run_detail.html',
        {
            'run': run,
            'errored': run.state == CrawlRun.State.ERROR,
            'allow_search_infinite': run.state == CrawlRun.State.NOT_STARTED and run.search_back_to,
            'can_cancel': run.state not in (CrawlRun.State.CANCELLED, CrawlRun.State.COMPLETE),
            'user_logged_in': request.user.is_authenticated,
        },
    )


@login_required
@require_POST
def run_remove_error_hx(request, run_id):
    run = get_object_or_404(CrawlRun, pk=run_id)

    if run.state == run.State.ERROR:
        if run.next_fetch:
            run.state = run.State.FETCHING_DECKS
        else:
            run.state = run.State.NOT_STARTED
        run.save()
    
    return HttpResponseClientRefresh()


@login_required
@require_POST
def run_remove_limit_hx(request, run_id):
    run = get_object_or_404(CrawlRun, pk=run_id)

    if run.state == run.State.NOT_STARTED:
        run.search_back_to = None
        run.save()
    
    return HttpResponseClientRefresh()


@login_required
@require_POST
def run_cancel_hx(request, run_id):
    run = get_object_or_404(CrawlRun, pk=run_id)

    if run.state != CrawlRun.State.COMPLETE:
        run.state = CrawlRun.State.CANCELLED
        run.save()
    
    return HttpResponseClientRefresh()


@login_required
@require_POST
def update_stats(request):
    legal_decks = (
        Deck.objects
        .filter(pdh_legal=True)
        .count()
    )

    s = SiteStat(legal_decks=legal_decks)
    s.save()
    
    return HttpResponseClientRefresh()


def log_index(request):
    logs = LogStart.objects.all()
    paginator = Paginator(logs, 10, orphans=3)
    page_number = request.GET.get('page')
    logs_page = paginator.get_page(page_number)

    return render(
        request,
        'crawler/log_index.html',
        {
            'logs': logs_page,
        },
    )


def log_errors(request):
    logs = (
        LogEntry.objects
        .filter(is_stderr=True)
        .order_by('-created')
    )

    paginator = Paginator(logs, 10, orphans=3)
    page_number = request.GET.get('page')
    logs_page = paginator.get_page(page_number)

    return render(
        request,
        'crawler/log_errors.html',
        {
            'logs': logs_page,
        },
    )


def log_one_error(request, logstart_id):
    return log_one(request, logstart_id, limit_to_errors=True)


def log_one(request, logstart_id, limit_to_errors=False):
    log_start = get_object_or_404(LogStart, pk=logstart_id)
    logs = (
        LogEntry.objects
        .filter(parent=log_start)
        .order_by('created')
    )
    if limit_to_errors:
        logs = logs.filter(is_stderr=True)

    paginator = Paginator(logs, 40, orphans=3)
    page_number = request.GET.get('page')
    logs_page = paginator.get_page(page_number)

    return render(
        request,
        'crawler/log.html',
        {
            'log_start': log_start,
            'logs': logs_page,
            'limited_to_errors': limit_to_errors,
        },
    )

crawler/templates/crawler/_start_archidekt_poll.html
<button hx-post="{% url 'crawler:run-archidekt-one' run_id %}"
hx-target="#resumeResult" hx-swap="beforeend" hx-trigger="every 2s"
class="btn btn-outline-primary me-2 disabled">All pages</button>

crawler/templates/crawler/index.html
{% extends 'base.html' %}
{% block title %}Crawler backstage{% endblock %}
{% block body %}
<div class="container" hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
  <nav aria-label="breadcrumb" class="mt-3">
    <ol class="breadcrumb">
      <li class="breadcrumb-item active" aria-current="page">Crawler backstage</li>
    </ol>
  </nav>
  <div class="mb-3">
    <a href="{% url 'crawler:log-index' %}" class="btn btn-primary">Logs</a>
    <a href="{% url 'crawler:run-index' %}" class="btn btn-secondary">Runs</a>
  </div>

  <hr>
  <div>
    {% if user_logged_in %}<button hx-post="{% url 'crawler:update-stats' %}" class="btn btn-outline-primary mb-2">Update site stats</button>{% endif %}
    Last update: {{ stats.timestamp|default:"--" }} //
    Legal decks: {{ stats.legal_decks|default:"--" }}
  </div>
</div>
{% endblock %}

crawler/templates/crawler/log.html
{% extends 'base.html' %}
{% block title %}Crawler admin — log {{ logs.0.id }}{% endblock %}
{% block body %}
<div class="container">
  <nav aria-label="breadcrumb" class="mt-3">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'crawler:index' %}">Crawler admin</a></li>
      <li class="breadcrumb-item"><a href="{% url 'crawler:log-index' %}">Logs</a></li>
      <li class="breadcrumb-item active" aria-current="page">#{{ log_start.id }}{% if limited_to_errors %} errors{% endif %}</li>
    </ol>
  </nav>
  <div class="mb-3">
    {% if limited_to_errors %}<a href="{% url 'crawler:log-one' log_start.id %}" class="btn btn-primary">Show all logs</a>{% endif %}
    {% if not limited_to_errors %}<a href="{% url 'crawler:log-one-errors' log_start.id %}" class="btn btn-primary">Limit to errors</a>{% endif %}
  </div>
  <table class="table">
    <tr><th>Timestamp</th><th>Line</th></tr>
    {% for log in logs %}
    <tr{% if log.is_stderr %} class="text-bg-danger"{% endif %}>
      <td>{{ log.created }}</a></td>
      <td>{{ log.text }}</td>
    </tr>
    {% empty %}
    <tr><td colspan="2">No logs found.</td></tr>
    {% endfor %}
  </table>
  <div class="mb-3">
    {% if logs.has_previous %}
    <a href="?page=1">first</a>
    <a href="?page={{ logs.previous_page_number }}">previous</a>
    {% endif %}
    (page {{ logs.number }} of {{ logs.paginator.num_pages }})
    {% if logs.has_next %}
    <a href="?page={{ logs.next_page_number }}">next</a>
    <a href="?page={{ logs.paginator.num_pages }}">last</a>
    {% endif %}   
  </div>
</div>
{% endblock %}

crawler/templates/crawler/log_errors.html
{% extends 'base.html' %}
{% block title %}Crawler admin — errors only{% endblock %}
{% block body %}
<div class="container">
  <nav aria-label="breadcrumb" class="mt-3">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'crawler:index' %}">Crawler admin</a></li>
      <li class="breadcrumb-item"><a href="{% url 'crawler:log-index' %}">Logs</a></li>
      <li class="breadcrumb-item active" aria-current="page">Errors</li>
    </ol>
  </nav>
  <table class="table">
    <tr><th>Log</th><th>Timestamp</th><th>Line</th></tr>
    {% for log in logs %}
    <tr>
      <td><a href="{% url 'crawler:log-one-errors' log.parent.id %}">{{ log.parent.id }}</a></td>
      <td>{{ log.created }}</td>
      <td>
        <div class="text-danger">{{ log.text|truncatechars:100 }}</div>
        <div class="text-secondary"><small>from <q>{{ log.parent.text|truncatechars:100 }}</q></small></div>
      </td>
    </tr>
    {% empty %}
    <tr><td colspan="2">No error logs found.</td></tr>
    {% endfor %}
  </table>
  <div class="mb-3">
    {% if logs.has_previous %}
    <a href="?page=1">first</a>
    <a href="?page={{ logs.previous_page_number }}">previous</a>
    {% endif %}
    (page {{ logs.number }} of {{ logs.paginator.num_pages }})
    {% if logs.has_next %}
    <a href="?page={{ logs.next_page_number }}">next</a>
    <a href="?page={{ logs.paginator.num_pages }}">last</a>
    {% endif %}   
  </div>
</div>
{% endblock %}

crawler/templates/crawler/log_index.html
{% extends 'base.html' %}
{% block title %}Crawler admin — logs{% endblock %}
{% block body %}
<div class="container">
  <nav aria-label="breadcrumb" class="mt-3">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'crawler:index' %}">Crawler admin</a></li>
      <li class="breadcrumb-item active" aria-current="page">Logs</li>
    </ol>
  </nav>
  <table class="table">
    <tr><th>Start time</th><th>First line</th></tr>
    {% for log in logs %}
    <tr>
      <td><a href="{% url 'crawler:log-one' log.id %}">{{ log.created }}</a></td>
      <td>{{ log.text|truncatechars:100 }}</td>
    </tr>
    {% empty %}
    <tr><td colspan="2">No logs found.</td></tr>
    {% endfor %}
  </table>
  <div class="mb-3">
    {% if logs.has_previous %}
    <a href="?page=1">first</a>
    <a href="?page={{ logs.previous_page_number }}">previous</a>
    {% endif %}
    (page {{ logs.number }} of {{ logs.paginator.num_pages }})
    {% if logs.has_next %}
    <a href="?page={{ logs.next_page_number }}">next</a>
    <a href="?page={{ logs.paginator.num_pages }}">last</a>
    {% endif %}   
  </div>
</div>
{% endblock %}

crawler/templates/crawler/run_detail.html
{% extends 'base.html' %}
{% block title %}Crawler admin — run {{ run.id }}{% endblock %}
{% block body %}
<div class="container" hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
  <nav aria-label="breadcrumb" class="mt-3">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'crawler:index' %}">Crawler admin</a></li>
      <li class="breadcrumb-item"><a href="{% url 'crawler:run-index' %}">Runs</a></li>
      <li class="breadcrumb-item active" aria-current="page">Run {{ run.id }} ({{ run.get_target_display }})</li>
    </ol>
  </nav>
  <ul class="list-group mb-3">
    <li class="list-group-item d-flex justify-content-between align-items-start">
      <div class="ms-2 me-auto">
        <div class="fw-bold">Began</div>
        {{ run.crawl_start_time }}
      </div>
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-start">
      <div class="ms-2 me-auto">
        <div class="fw-bold">Search back to</div>
        {% if run.search_back_to %}{{ run.search_back_to }}{% else %}no limit{% endif %}
        {% if allow_search_infinite and user_logged_in %}
        <br><button class="btn btn-outline-secondary" hx-post="{% url 'crawler:run-remove-limit' run.id %}">Remove limit</button> (to re-crawl everything)
        {% endif %}
      </div>
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-start">
      <div class="ms-2 me-auto">
        <div class="fw-bold">State</div>
        {{ run.get_state_display }}
        {% if can_cancel and user_logged_in %}
        <br><button class="btn btn-outline-danger"
          hx-post="{% url 'crawler:run-cancel' run.id %}"
          hx-confirm="Are you sure you want to cancel this run?">Cancel run</button>
        {% endif %}
      </div>
    </li>

    {% if run.next_fetch and user_logged_in %}
    <li class="list-group-item d-flex justify-content-between align-items-start">
      <div class="ms-2 me-auto">
        <div class="fw-bold">Next URL</div>
        <code>{{ run.next_fetch }}</code>
      </div>
    </li>
    {% endif %}

    {% if run.note %}
    <li class="list-group-item d-flex justify-content-between align-items-start">
      <div class="ms-2 me-auto">
        <div class="fw-bold">Note</div>
        {{ run.note }}
      </div>
    </li>
    {% endif %}

    {% if errored %}
    <li class="list-group-item d-flex justify-content-between align-items-start">
      <div class="ms-2 me-auto">
        <div class="fw-bold">Clear error</div>
        {% if user_logged_in %}<button class="btn btn-outline-danger me-2" hx-post="{% url 'crawler:run-remove-error' run.id %}">Clear error</button>{% endif %}
      </div>
    </li>
    {% endif %}
  </ul>
</div>
{% endblock %}

crawler/templates/crawler/run_index.html
{% extends 'base.html' %}
{% block title %}Crawler admin — runs{% endblock %}
{% block body %}
<div class="container" hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
  <nav aria-label="breadcrumb" class="mt-3">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'crawler:index' %}">Crawler admin</a></li>
      <li class="breadcrumb-item active" aria-current="page">Runs</li>
    </ol>
  </nav>
  <table class="table">
    <tr><th>Start time</th><th>Target</th><th>State</th><th>Search back to</th></tr>
    {% for run in runs %}
    <tr>
      <td><a href="{% url 'crawler:run-detail' run.id %}">{{ run.crawl_start_time }}</a></td>
      <td>{{ run.get_target_display }}</td>
      <td>{{ run.get_state_display }}</td>
      <td>{% if run.search_back_to %}{{ run.search_back_to }}{% else %}no limit{% endif %}</td>
    </tr>
    {% empty %}
    <tr><td colspan="4">No runs found.</td></tr>
    {% endfor %}
  </table>
  <div class="mb-3">
    {% if runs.has_previous %}
    <a href="?page=1">first</a>
    <a href="?page={{ runs.previous_page_number }}">previous</a>
    {% endif %}
    (page {{ runs.number }} of {{ runs.paginator.num_pages }})
    {% if runs.has_next %}
    <a href="?page={{ runs.next_page_number }}">next</a>
    <a href="?page={{ runs.paginator.num_pages }}">last</a>
    {% endif %}   
  </div>
</div>
{% endblock %}